services:
  postgres:
    container_name: transit-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: transit
      POSTGRES_PASSWORD: transit
      POSTGRES_DB: transitdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
